# Generated by Django 3.2.19 on 2023-08-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.TextField(default=None, unique=True)),
                ('line_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_updated', models.DateTimeField(auto_created=True)),
                ('machine_name', models.TextField(default=None)),
                ('machine_number', models.IntegerField(unique=True)),
                ('ok_count', models.IntegerField(default=0)),
                ('ng_count', models.IntegerField(default=0)),
                ('machine_in_which_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.line_1')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.TextField(default=None, unique=True)),
                ('plant_location', models.TextField(default=None)),
                ('plant_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.TextField(default=None, unique=True)),
                ('shop_number', models.IntegerField(default=1)),
                ('shop_in_which_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.plant_1')),
            ],
        ),
        migrations.CreateModel(
            name='shift_1_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.machines')),
            ],
        ),
        migrations.AddField(
            model_name='line_1',
            name='line_in_which_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.shop_1'),
        ),
    ]
