# Generated by Django 3.2.19 on 2023-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='shift_1_ng_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machines',
            name='shift_1_ok_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machines',
            name='shift_2_ng_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machines',
            name='shift_2_ok_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='last_date_updated',
            field=models.DateField(auto_created=True),
        ),
    ]
