# Generated by Django 3.2.19 on 2023-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20230814_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='last_date_updated',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
